project:
  type: website
  output-dir: _site

website:
  title: "Chathu Bandara"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: skills.qmd
        text: Skills
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles/main.css
    toc: false
    page-layout: full


    